version: '3.3'
services:
  db:
    container_name: pgdb
    image: postgres:12.12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5433
    ports:
      - '5432:5433'
    volumes:
      - db:/var/lib/postgresql/data
#    networks:
#      - backend

volumes:
  db:
    driver: local

networks:
  backend:
    driver: bridge