version: '3.7'
services:
  joinfut-backend:
    image: joinfut/backend:latest
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - DB_URL=jdbc:postgresql://127.0.0.1:5434/joinfut
      - DB_DDL=UPDATE

networks:
  backend:
    external: true
    driver: bridge